#!/usr/bin/env bash
features/run/memory && \
features/run/dom-memory && \
features/run/http-memory && \
features/run/dom-http-memory && \
features/run/webdriver-memory && \
features/run/browserstack-memory
