#!/usr/bin/env bash
if [[ -z "${BROWSERSTACK_USER}" ]]; then
  echo "set BROWSERSTACK_USER and BROWSERSTACK_KEY to run features on browserstack"
else
  CUCUMBER_ASSEMBLY=browserstack-memory node node_modules/.bin/cucumber-js "$@"
fi
